openapi: 3.0.0
info:
  title: License API
  version: 1.0.0
paths:
  /licenses:
    post:
      summary: Create a new license
      operationId: CreateLicense
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/License"
      responses:
        "201":
          description: License created
  /licenses/{shortname}:
    patch:
      summary: Update an existing license
      operationId: UpdateLicense
      parameters:
        - name: shortname
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/License"
      responses:
        "200":
          description: License updated
components:
  schemas:
    License:
      type: object
      required:
        - shortname
        - fullname
      properties:
        shortname:
          type: string
        fullname:
          type: string
        text:
          type: string
        url:
          type: string
